// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 06/08/2024, 22:31:52
const configMerger = require("C:/Users/Nathalya/Documents/GitHub/Vue/vue-project/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["C:/Users/Nathalya/Documents/GitHub/Vue/vue-project/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Nathalya/Documents/GitHub/Vue/vue-project/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Nathalya/Documents/GitHub/Vue/vue-project/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Nathalya/Documents/GitHub/Vue/vue-project/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Nathalya/Documents/GitHub/Vue/vue-project/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Nathalya/Documents/GitHub/Vue/vue-project/plugins/**/*.{js,ts,mjs}","C:/Users/Nathalya/Documents/GitHub/Vue/vue-project/composables/**/*.{js,ts,mjs}","C:/Users/Nathalya/Documents/GitHub/Vue/vue-project/utils/**/*.{js,ts,mjs}","C:/Users/Nathalya/Documents/GitHub/Vue/vue-project/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Nathalya/Documents/GitHub/Vue/vue-project/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Nathalya/Documents/GitHub/Vue/vue-project/app.config.{js,ts,mjs}"] }));

module.exports = config
